"""
Comprehensive File Description Generator

Author: Madhurima Rawat
Description:
This script reads a directory structure from a Markdown (.md) file 
and generates automatic descriptions based on file names and extensions.

Supported File Types:
- Documents: .txt, .md, .docx, .pdf, .xlsx, .csv, .word, .ppt, .pptx
- Jupyter Notebooks: .ipynb, .ipynb_checkpoints
- Code Files: .py, .java, .c, .cpp, .html, .css, .js, .rb, .swift, .ts, .dart, .r, .scala, .pl, .sh, .bat, .ps1, .lua, .go, .rs, .asm, .tsc, .m, .for, .vhd
- Web & Graphics: .webp, .png, .jpg, .svg, .gif, .ico, .bmp, .tiff
- Configuration: .ini, .cfg, .toml, .yaml, .sh, .bat, .conf, .editorconfig, .clang-format, .clippy.toml, .rustfmt.toml
- Data Files: .json, .xml, .log, .parquet, .data, .pkl, .h5, .csv.gz
- Media Files: .png, .jpg, .gif, .mp4, .mp3
- Version Control: .gitignore, .gitattributes, .mailmap
- Web Development: .php, .asp, .jsp
- Database Files: .db, .sqlite, .sql, .mdb
- Build & Make: .makefile, .cmake, .kconfig, .kbuild
- Compilation/Binaries: .o, .so, .dll, .exe, .bin, .hex
- Archives & Compression: .zip, .tar, .gz, .bz2, .7z, .rar
- Fonts: .ttf, .otf
- CAD & 3D Model Files: .dwg, .stl, .obj
- Disk Images: .iso, .vmdk, .qcow2

Input: directory_structure.md (generated by directory tree script)
Output: directory_with_descriptions.md (includes file descriptions)
"""

import os


# --------------------------- FILE DESCRIPTION FUNCTION --------------------------- #
def generate_description(file_name):
    """
    Generates a brief description based on file type and name.

    Parameters:
    - file_name (str): The name of the file (including extension).

    Returns:
    - str: A generated description for the file.
    """

    descriptions = {
        # Document Files
        ".txt": "Plain text file, contains notes or logs.",
        ".md": "Markdown file, used for documentation.",
        ".docx": "Microsoft Word document, contains formatted text.",
        ".word": "Word document file, alternative to .docx.",
        ".pdf": "PDF document, used for reports, scanned files, or official documents.",
        ".xlsx": "Excel spreadsheet, used for structured data and analysis.",
        ".csv": "Comma-Separated Values file, used for tabular data storage.",
        ".ppt": "PowerPoint presentation file.",
        ".pptx": "PowerPoint presentation file (newer format).",
        # Jupyter Notebooks
        ".ipynb": "Jupyter Notebook file, contains Python code and markdown cells.",
        ".ipynb_checkpoints": "Checkpoint file auto-saved by Jupyter Notebook.",
        # Programming & Code Files
        ".py": "Python script, used for automation and software development.",
        ".java": "Java source file, part of a Java project.",
        ".c": "C language source file, used for system programming.",
        ".cpp": "C++ source file, used for application and system development.",
        ".html": "HTML file, defines web page structure.",
        ".css": "CSS file, contains styles for web pages.",
        ".js": "JavaScript file, adds interactivity to web pages.",
        ".rb": "Ruby source file, used for web applications.",
        ".swift": "Swift source file, used for iOS/macOS application development.",
        ".ts": "TypeScript source file, a typed superset of JavaScript.",
        ".dart": "Dart source file, used for Flutter applications.",
        ".r": "R script, used for statistical computing and data analysis.",
        ".scala": "Scala source file, used for scalable applications.",
        ".pl": "Perl script, used for text processing and system administration.",
        ".sh": "Shell script, used for automation in Unix/Linux.",
        ".bat": "Batch script, used for Windows command-line automation.",
        ".ps1": "PowerShell script, used for automation in Windows environments.",
        ".lua": "Lua script file, used for embedded applications and game development.",
        ".go": "Go language source file, used for building high-performance applications.",
        ".rs": "Rust source file, used for safe and concurrent system development.",
        ".asm": "Assembly language source file, used for low-level programming.",
        ".tsc": "Transpiled TypeScript file.",
        ".m": "MATLAB or Objective-C source file.",
        ".for": "Fortran source file.",
        ".vhd": "VHDL file, used for hardware design.",
        # Web & Graphics
        ".webp": "WebP image file, used for high-quality web graphics with small file size.",
        ".png": "PNG image file, used for high-quality images with transparency support.",
        ".jpg": "JPEG image file, used for photos and web graphics.",
        ".svg": "Scalable Vector Graphics file, used for vector images and web icons.",
        ".gif": "GIF image file, used for animations and simple images.",
        ".ico": "Icon file, used for application and website favicons.",
        ".bmp": "Bitmap image file, used for raster graphics.",
        ".tiff": "TIFF image file, used for high-resolution images.",
        # Configuration & System Files
        ".ini": "Configuration file, contains settings for software applications.",
        ".cfg": "Configuration file, used to store parameters and options.",
        ".toml": "TOML configuration file, used for project settings.",
        ".yaml": "YAML configuration file, widely used in DevOps and Kubernetes.",
        ".conf": "Configuration file, used for system and server settings.",
        ".editorconfig": "EditorConfig file, defines coding style preferences.",
        ".clang-format": "Clang format file, defines coding style rules.",
        ".clippy.toml": "Clippy configuration file, used for Rust linting rules.",
        ".rustfmt.toml": "Rust formatting configuration file.",
        ".gitattributes": "Git attributes file, defines repository behaviors.",
        ".gitignore": "Git ignore file, specifies files to be ignored by Git.",
        ".mailmap": "Mailmap file, used for author name corrections in Git.",
        # Data & Machine Learning Files
        ".json": "JSON file, used for structured data storage.",
        ".xml": "XML file, used for structured data storage and configuration.",
        ".log": "Log file, used for recording system or application events.",
        ".parquet": "Parquet data file, optimized for big data storage and processing.",
        ".data": "Raw data file, used for storing large datasets.",
        ".pkl": "Pickle file, used for storing serialized Python objects like machine learning models.",
        ".h5": "HDF5 data file, used in machine learning and big data.",
        ".csv.gz": "Compressed CSV file, used for large dataset storage.",
        # Web Development & Server-side Scripts
        ".php": "PHP script, used for server-side web applications.",
        ".asp": "ASP file, used for Microsoft web applications.",
        ".jsp": "JSP file, Java Server Pages for dynamic web content.",
        # Database Files
        ".db": "Database file, used for storing structured data.",
        ".sqlite": "SQLite database file.",
        ".sql": "SQL script, used for database management.",
        ".mdb": "Microsoft Access database file.",
        # Build & Makefiles
        ".makefile": "Makefile, defines build automation instructions.",
        ".cmake": "CMake file, used for cross-platform build configuration.",
        ".kconfig": "Kernel configuration file, used in Linux kernel builds.",
        ".kbuild": "Kernel build file, part of the Linux build system.",
        # Compilation & Binaries
        ".o": "Object file, generated during compilation.",
        ".so": "Shared object file, used in dynamic linking.",
        ".dll": "Dynamic link library, used in Windows applications.",
        ".exe": "Executable file, used for running Windows applications.",
        ".bin": "Binary file, used for storing compiled machine code.",
        ".hex": "Hexadecimal file, used for embedded systems and firmware storage.",
        # Archives & Compression
        ".zip": "ZIP compressed archive, used for packaging multiple files.",
        ".tar": "TAR archive, used for file packaging in Unix systems.",
        ".gz": "GZIP compressed file, used for file compression in Unix/Linux.",
        ".bz2": "Bzip2 compressed file, used for higher compression efficiency.",
        ".7z": "7z archive file, used for high compression ratio packaging.",
        ".rar": "RAR compressed archive, used for file compression and storage.",
        # Fonts
        ".ttf": "TrueType font file, used for scalable fonts.",
        ".otf": "OpenType font file, used for advanced typography.",
        # CAD & 3D Model Files
        ".dwg": "AutoCAD drawing file, used in engineering design.",
        ".stl": "STL file, used for 3D printing and modeling.",
        ".obj": "3D model file, used in graphics applications.",
        # Disk Images
        ".iso": "ISO disk image file, used for creating bootable media.",
        ".vmdk": "VMware virtual disk file, used in virtual machines.",
        ".qcow2": "QEMU disk image file, used for virtual machines.",
    }

    # Check if the name itself is `.ipynb_checkpoints` (folder)
    if file_name == ".ipynb_checkpoints":
        return "Folder containing Jupyter Notebook checkpoint versions."

    ext = os.path.splitext(file_name)[1].lower()  # Extract file extension
    return descriptions.get(
        ext, "Unknown file type or custom file."
    )  # Default description


# --------------------------- PROCESS DIRECTORY STRUCTURE --------------------------- #
def process_directory_structure(input_file, output_file):
    """
    Reads a directory structure from a Markdown file and appends descriptions.

    Parameters:
    - input_file (str): Path to the input .md file containing the directory tree.
    - output_file (str): Path to save the output .md file with descriptions.
    """

    with open(input_file, "r", encoding="utf-8") as f:
        lines = f.readlines()

    with open(output_file, "w", encoding="utf-8") as f:

        for line in lines:
            stripped_line = line.strip()
            if "." in stripped_line:  # Likely a file
                file_name = stripped_line.split(" ")[-1]
                description = generate_description(file_name)
                f.write(f"{line.strip()}  →  {description}\n")
            else:
                f.write(line)  # Keep folder structure unchanged

    print(f"\n✅ File descriptions added and saved to {output_file}")


# --------------------------- RUN SCRIPT --------------------------- #
if __name__ == "__main__":
    input_md = (
        "Directory_File_Structure_Lister_Tree.md"  # Existing directory structure file
    )

    output_md = "Directory_With_Descriptions.md"  # Output file with descriptions

    process_directory_structure(input_md, output_md)
