"""
Directory Structure Generator

Author: Madhurima Rawat
Description: This script generates a structured directory tree for:
    - Local file system directories
    - Public GitHub repositories

The output is saved in a Markdown (`.md`) file in a tree format.
"""

import os
import requests


# --------------------------- LOCAL DIRECTORY FUNCTION --------------------------- #
def print_directory_tree(root_dir, indent="", output_file=None):
    """
    Recursively generates and prints the directory structure of a local folder.

    Parameters:
    - root_dir (str): The path to the local directory.
    - indent (str): Formatting string for indentation in the tree structure.
    - output_file (file object, optional): The file to which output should be written.
    """
    try:
        items = sorted(os.listdir(root_dir))  # Sort files/folders for consistency
        for index, item in enumerate(items):
            path = os.path.join(root_dir, item)
            is_last = (
                index == len(items) - 1
            )  # Check if this is the last item in the folder

            # Formatting for tree structure
            prefix = "└── " if is_last else "├── "
            line = indent + prefix + item

            print(line)  # Print to console
            if output_file:
                output_file.write(line + "\n")  # Write to file

            if os.path.isdir(path):  # If the item is a folder, recurse into it
                new_indent = indent + ("    " if is_last else "│   ")
                print_directory_tree(path, new_indent, output_file)
    except Exception as e:
        print(f"❌ Error: {e}")


# --------------------------- GITHUB FUNCTION --------------------------- #
def list_github_repo(owner, repo, indent="", output_file=None):
    """
    Fetches and prints the full directory structure of a public GitHub repository.

    Parameters:
    - owner (str): The username or organization that owns the repository.
    - repo (str): The name of the repository.
    - indent (str): Formatting string for indentation in the tree structure.
    - output_file (file object, optional): The file to which output should be written.

    Note:
    - Works only for **public** repositories.
    - Uses GitHub's API to traverse directories recursively.
    """
    base_url = f"https://api.github.com/repos/{owner}/{repo}/git/trees/main?recursive=1"

    try:
        response = requests.get(base_url)

        if response.status_code == 200:
            data = response.json()
            tree = data.get("tree", [])

            paths = sorted(
                [item["path"] for item in tree]
            )  # Sort paths for consistency
            printed_folders = set()
            last_seen_depth = -1

            for path in paths:
                parts = path.split("/")
                depth = len(parts) - 1

                # Handle indentation with │ for subdirectories
                indent_str = "│   " * depth

                # Determine if it's the last item in the folder
                is_last = path == paths[-1] or not any(
                    p.startswith("/".join(parts[:-1]) + "/")
                    for p in paths[paths.index(path) + 1 :]
                )
                prefix = "└── " if is_last else "├── "

                line = indent_str + prefix + parts[-1]

                print(line)
                if output_file:
                    output_file.write(line + "\n")

                printed_folders.add(path)

        else:
            print(
                f"❌ Error: Unable to access repository (HTTP {response.status_code})"
            )

    except Exception as e:
        print(f"❌ Error accessing GitHub repository: {e}")


# --------------------------- MAIN FUNCTION --------------------------- #
def main(source_type, source_path):
    """
    Handles generating a directory structure from a local folder or a GitHub repository.

    Parameters:
    - source_type (str): Type of source ("local" for a local directory, "github" for a GitHub repo).
    - source_path (str): Path to the directory (for local) or "owner/repo" format (for GitHub).

    Output:
    - Saves the directory structure in `Directory_File_Structure_Lister_Tree` in Markdown format.
    """
    output_md_file = "Directory_File_Structure_Lister_Tree.md"

    with open(output_md_file, "w", encoding="utf-8") as f:
        f.write("```\n")  # Start Markdown code block
        f.write(f"Generated by: Madhurima Rawat\n\n")

        if source_type == "local":
            f.write(f"Local Directory: {source_path}\n")
            print_directory_tree(source_path, output_file=f)

        elif source_type == "github":
            owner, repo = source_path.split("/")
            f.write(f"GitHub Repository: {source_path}\n")
            list_github_repo(owner, repo, output_file=f)

        f.write("```\n")  # End Markdown code block

    print(f"\n✅ Directory structure saved in {output_md_file}")


# --------------------------- RUN SCRIPT --------------------------- #
if __name__ == "__main__":
    # Example 1: Generate directory tree for a local folder
    # main("local", r"C:\Users\rawat\Documents\Internship\Completed\IIT Bhilai Internship")

    # Example 2: Generate directory tree for a public GitHub repository
    main("github", "madhurimarawat/Python-for-Datascience")
